services:
  postgres:
    image: postgres:16
    container_name: grid07-postgres
    restart: always
    environment:
      POSTGRES_DB: grid07
      POSTGRES_USER: grid07_user
      POSTGRES_PASSWORD: grid07_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: grid07-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: